---
abstract: "Pure Perl implementation of MongoDB's BSON serialization"
author:
  - 'minimalist <minimalist@lavabit.com>'
build_requires:
  DateTime: 0
configure_requires:
  ExtUtils::MakeMaker: 0
distribution_type: module
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.57_05'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: BSON
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
  Tie::IxHash: 0
resources:
  repository: git://github.com/naturalist/Perl-BSON.git
  bugtracker: https://github.com/naturalist/Perl-BSON/issues
version: 0.02
